### ISSUE TITLE
Suggest a better name for this project

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-static-boilerplate#26]

**Comment by dsernst** [comment]
What's wrong with the current name?

**Comment by n8sabes** [comment]
React Static Boilerplate is a clear and descriptive name, but will think about ideas. You might want to write a more clear value proposition in the description to attract people to the project. By highlighting the benefits ahead of the technologies, developers can more easily understand what you’re offering them. For example:


"React Static Boilerplate (RSB) accelerates the development of stand-alone web applications for a serverless architecture. RSB significantly reduces cost by eliminating the need for servers such as EC2 instances because the entire site can be hosted directly from AWS S3 storage, GitHub, Firebase, or other similar cloud storage. Sites built with RSB can be fully functional with REST API calls to micro-services such as Amazon Lambda, or dynamic Docker endpoints. RSB is build with upon best of breed technologies including; React.js, postCSS, Sass, ES6+, Babel 6, Webpack, BrowerSync, React Hot Loader and more."


Additionally, you might want to align your project with complimentary micro-services projects such as Serverless.com.

Possible names:

R E S T a t i c  — Meaning a React REST/API Static Site

H Y P E R S T A T I C
