### ISSUE TITLE
Offline support (PWA)

### ISSUE THREAD

**Issue by patrick-samy** [kriasoft/react-static-boilerplate#263]
Hey folks, fantastic project, a great starting point for Relay-based static web apps!

Any plans to support offline-mode? And other progressive web app features?

**Comment by frenzzy** [comment]
But this functionality already in place, the same as in create-react-app, docs:
[Create React App -> Making a Progressive Web App](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app)

**Comment by patrick-samy** [comment]
Actually, the store doesn't seem to be rehydrated when reloading the app.

Any suggestions on how to do this with Relay?

**Comment by koistya** [comment]
@patrick-samy one option is to pre-render the app on the server, hydrate relay.fetch response / inject it into the page, upon the initial page load on the client, instead of actually fetching data from a GraphQL backend via Ajax, just make it return the cached (dehydrated) response (using cacheConfig), and reset this behaviour to default for the next calls to relay.fetch

**Comment by patrick-samy** [comment]
@koistya thanks, I'm working on a serverless app though!

However, it seems like a similar concept with QueryResponseCache on the client-side would work:
http://taiki-t.hatenablog.com/entry/2017/09/05/181931
