### ISSUE TITLE
Suggestion: Provide critical HTML snippet for the homepage

### ISSUE THREAD

**Issue by heeton** [kriasoft/react-static-boilerplate#35]
Much like the critical CSS idea, how about giving first-time visitors the absolutely fastest possible experience by designating a small chunk of HTML + CSS which is sent over the wire first. This reduces transport times, extra CSS loads, page rendering time (especially on long/complex homepages). 

The react app then loads everything else, and loads the rest of the content in place. A hook would be needed for a CSS transition (fade in, or something like [this](https://facebook.github.io/design/ios9.html)).

**Comment by vnglst** [comment]
+1

**Comment by thejmazz** [comment]
You would lose SEO for the non critical HTML though, but a nice idea.

**Comment by koistya** [comment]
This should be pretty easy to implement with Relay, a little bit harder with custom Ajax tools. For example, on a message board page you need to make sure that only top X topic are actually loaded and number of comments, when that page is mounted into the dom, you can fetch and display more data (e.g. last three comments for each topic) inside the `componentDidMount()` event handler.

I'm closing this issue because it was open for some time. Feel free to continue this discussion or re-open if you have a concrete feature in mind to make implementing progressive enhancement easier.
