### ISSUE TITLE
Q: how to load "main.css" from the static page?

### ISSUE THREAD

**Issue by dvdplm** [kriasoft/react-static-boilerplate#49]
What is the best practise to load the css bundle (with a hashed filename) in the statically generated pages?

The `<Html>` component currently does not load any CSS at all, is that expected? Should we be using `html-webpack-plugin` for this and generate a skeleton template?

**Comment by dsernst** [comment]
See how [Layout.js](https://github.com/koistya/react-static-boilerplate/blob/cc2da061a4b4424041f8652132f37c707fd0376c/components/Layout/Layout.js#L8) imports its stylesheet:

```js
import React, { PropTypes } from 'react';
import './Layout.scss';
```

This causes that file to get inlined as a `<style>` element in the rendered content.

Does this answer your question? Or did I misunderstand?

**Comment by dvdplm** [comment]
> Does this answer your question? Or did I misunderstand?

Well, not really. I would like all my css to be 1. bundled&minified; 2. included with a `<link>` on all pages. The `ExtractTextPlugin` takes care of extracting all styles and creates a bundled css. It's not clear (to me) what the best way is to include that in all static pages rendered.

**Comment by Samueldhardy** [comment]
bump

**Comment by ncksllvn** [comment]
I believe PR #41 addresses this but I think that code could be cleaned up a bit.

**Comment by koistya** [comment]
There are different routes to optimize the initial page load time. The approach that is currently used in RSB tries to minimize the number of external resources needed to be loaded initially (when user opens the page for the first time). For that reason, all the CSS for each chunk is bundled into JavaScript (.js) file(s). So instead of:

```html
<link rel="stylesheet" href="/dist/main.5a4bf4f88305456d34fd.css">
<script src="/dist/main.5a4bf4f88305456d34fd.js"></script>
```

You can have just:

```html
<script src="/dist/main.5a4bf4f88305456d34fd.js"></script>
```

As far as I understand, `ExtractTextPlugin` doesn't work well with chunks and causes unnecessary excess HTTP requests.

If you have a suggestion how to optimize the initial page load time that is oriented towards minimizing application bundle(s) (chunks) and redundant HTTP requests, please don't hesitate to share your ideas here or on [Gitter](https://gitter.im/kriasoft/react-static-boilerplate). Thanks! I will close this issue for now.
