### ISSUE TITLE
Update on blog index route - FIXED

### ISSUE THREAD

**Issue by ohNegative** [kriasoft/react-static-boilerplate#81]
In case anybody else was having issues with the route not working for the blog index page, all you have to do is change the name of the index.js file in the blog folder to something like: blog-index, or blog-main and then you can hit the[ http://localhost:3000/blog/blog-index]( http://localhost:3000/blog/blog-index) page where you can list the two blog posts. 

If you go to [http://localhost:3000/blog/index](http://localhost:3000/blog/index) you get an error. 

Anyways, thought this might help future peeps downloading this and wondering why its not working.

Pete

**Comment by deakster** [comment]
I think in this scenario people would typically prefer the blog index page to be at /blog rather than something like /blog/blog-index, which is longer and uglier.

To achieve that, you can take the `pages/blog/index.js` file and move+rename it to just `pages/blog.js`. 

Then the blog index page is at the top level [http://localhost:3000/blog](http://localhost:3000/blog) and the blog posts are [http://localhost:3000/blog/test-article-one](http://localhost:3000/blog/test-article-one) etc as expected.

**Comment by koistya** [comment]
The routing boilerplate has been refactored, here is the doc explaining how it works:

https://github.com/kriasoft/react-static-boilerplate/blob/master/docs/routing-and-navigation.md

And here is a live demo:

https://rsb.kriasoft.com

Feel free to re-open, if this issues still exists.
