### ISSUE TITLE
Not support live-reloading?

### ISSUE THREAD

**Issue by zzswang** [kriasoft/react-static-boilerplate#91]
1. npm start
2. change file components/header.js
3. browser doesn't reload automatically

**Comment by koistya** [comment]
The hot reloading functionality is mostly configured but the core peace that reloads the App is commented out, will need to fix that:

https://github.com/koistya/react-static-boilerplate/blob/master/core/app.js#L23-L31

**Comment by upq** [comment]
+1 for live reload

**Comment by koistya** [comment]
Oh, there is one more thing to live reload.. I think that code splitting should be disabled in order to make React Hot Loader work with Webpack 2.x.. trying to figure out, what the best way to do it. For example, live reload can be enabled by default when you run `npm start`, or maybe it's better to add a flag for it, like `npm run -- --hmr` or something like that, so you could test the site with Live Reload (requires modifications to the bundle), and also without Live Reload, where website will look more to what is actually going to be deployed.

**Comment by upq** [comment]
I think adding a flag is a good idea

**Comment by koistya** [comment]
@zzswang @upq I think Hot Module Replacement (HMR) and React Hot Loader should work fine now, please let me know if there are still any issues. This is enabled by default when you launch the project by running:

```sh
$ node run              # same as `node run start`, `npm start`
```

There is also `--no-hmr` flag that effectivly disables "live reload":

```sh
$ node run --no-hmr     # same as `nor run star --no-hmr`, `npm start -- --no-hmr`
```
