### ISSUE TITLE
dependencies/devDependencies unnecessarily split?

### ISSUE THREAD

**Issue by JeffreyATW** [kriasoft/react-static-boilerplate#99]
Hi @koistya, I'm wondering why some dependencies have been split out into `devDependencies`.

I understand that the ones remaining in `dependencies` are the ones necessary for the client-side JS to run, but since this is a static site generator, I don't understand why any environment that needs `package.json` would want to only install the production modules. Is this a Firebase-related change, or something else?

**Comment by koistya** [comment]
@JeffreyATW it's done solely for readability so that a developer opening this project for the first time could instantly see what dependencies are actually used in the app, and what are used during build or publishing. And for developers already familiar with this project, it also helps to have a clear picture how many actual (runtime) dependencies the project has.

**Comment by JeffreyATW** [comment]
Makes sense. I'll just make sure not to use the `--production` flag when using `npm install` in certain environments. Thanks!
